apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:VSOJcjsElhAUQ5Hk2oM3YHxZksa+jsh7vWfRnfa5oHSVNYKYxE6UqA==,iv:kS64AFsSRqYzyA4JJW0P2nFL9oIV5sehQE3wFONpp2M=,tag:RomAeRxuUB77R7lgPNah5A==,type:str]
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZTdNd2FPZElueHp4cGhD
            SHNaMVBzRnpDNmZQM2o1V0NGY1pMeHVlV2kwCkR2Yk1qaWgzajQ5UFp6VlREVDk5
            MWk4MXRSVi9PQnF1cFpUOHIyVVBESDgKLS0tIFdzT1Z3R3NNUUhmeEhZN0dKYjdn
            WWtDdWRVbkFHT2xodjRLcWNGVzJmSjAKnZGUs9YoRq2JBTEHRzxV9UxchRPHnmYL
            xLRf5BnMjQ+LETaqzbXVgWztDIXQAwMnzN/0YChKsvbv06BzhsxCaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T04:37:38Z"
    mac: ENC[AES256_GCM,data:KPPwbUqEsswRd17DoY/15aqwMnu9btlzzl1UH6u7HyUW09ErrJFki0ua05O/b0YTtC5UfYnGa92xjh4FTKFS16xARzj1IbVO2CjvceMvocH2/sjr1044v3M6sCrouzLrSEJ30tfn/xU8sBB8TDTlJ4hCEYMB/cvxwGh0rYGft3A=,iv:+3U28ISXQQg03s7vXKymV19I9fran2dIYWNBAqTigd4=,tag:HNaXJHCaNnZtAEwZODNczg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
