apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-api-token.yaml
  - clusterissuer-letsencrypt-dns-staging.yaml
  - clusterissuer-letsencrypt-dns-prod.yaml
  - etiennes-dev-wildcard-cert.yaml