apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsUser: 1000 # node uid
        runAsGroup: 1000 # node gid
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.32.1
          ports:
          - containerPort: 3005
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /audiobooks
              name: audiobookshelf-audiobooks
            - mountPath: /podcasts
              name: audiobookshelf-podcasts
            - mountPath: /config
              name: audiobookshelf-config
            - mountPath: /metadata
              name: audiobookshelf-metadata
          envFrom:
            - configMapRef:
                name: audiobookshelf-config
            #- secretRef:
            #    name: audiobookshelf-container-env
      volumes:
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
        - name: audiobookshelf-podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts-pvc
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
