apiVersion: v1
kind: Secret
metadata:
    name: backend-qts-secret
    namespace: qnap-trident
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:KIfwOhQzbEU=,iv:YntOql6kwzJH1RLZGtqHx/BJy5uuxaOOW2ipUMFbOjY=,tag:ftF+83UOJyre90wBNbvY6w==,type:str]
    password: ENC[AES256_GCM,data:CkdisgzjqmCw,iv:PtWybjlZji+TkadmHuhIlUoS3GwuEq9bXmlJCuoSH18=,tag:U+MiRDADSazHcS5HUD+xzA==,type:str]
    #ENC[AES256_GCM,data:KafgFr+sYEM3rw0PyaHuoRNP,iv:D+cgFzI4qkqD/5OiTRZUNQNJ3jOuX9D98Qq6dEuS2pk=,tag:fZrEClylfgI+WS90jSIGhw==,type:comment]
    storageAddress: ENC[AES256_GCM,data:cp57OcAXy65xBHJxlA==,iv:g4ezj7JENV9dVUNz9mcU+vH+B3wQCG1RyD4y2We938Q=,tag:ZNBW2Bp6TfAHiR1qp5Trcg==,type:str]
    https: ENC[AES256_GCM,data:+aig4+k=,iv:6XINAnn10ob9wvE41RW03yyCyc+4W/u6m7UueNxLENI=,tag:W2zpVUvqQzGAhxEli/MFDA==,type:str]
    port: ENC[AES256_GCM,data:hea9IQ==,iv:nLxcYB6GKVdO+bz1WiZxhL5VFlP7YdqtCcmdutZCJ5Q=,tag:gC1Lke+EZDPLZMWy7046uw==,type:str]
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZDdpS3Q0UFRZMGpqM21Z
            eGMwSEo1Z3k3TTRsOGZYQVVMRWpBc1J4b1FJCm5zSnJMRHhSckdvbFJYVXhSMGIz
            d0wzTmVibHdrRDZsZzZZMjB6dUhUcGMKLS0tIFpxcVVkN3ZQOGpqOHcrVjVzTGZI
            WmJXYkc2UXZadk9EZmR2YXF0TFJKY1UKamoFKhZZvBznbP85g8vgMGG1+9JZguuH
            KcmHGTzFdmkCHgO6qlBmqBMATMMp0AqSyQA5PJPgq/lDp6UcKOI2Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T23:04:34Z"
    mac: ENC[AES256_GCM,data:wUsMVv3uYIodNCZgFM7EFbnN9bROYwQMsNMqm4coRaVY5Oo7Z2MBGOCsW7dgsCXgL5g2Cf1CttUrxCqDSn+Ybn7cKda4aErwflDd2cryjT1f/Mts5m8OFlk9SgmPzac2LKglQnWH/uzWwxb0IfNl2lpPzGTxtHgg6xbD7tl6KtU=,iv:IM6TRPGq9ouXiz1cMgvKK7r/ubINzSFaX+7MJOiKeu4=,tag:idQWE7TVUseLR3jlxk1ADQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
    name: backend-qts
    namespace: qnap-trident
spec:
    version: 1
    storageDriverName: qnap-iscsi
    backendName: qts
    networkInterfaces:
        # optional
        - Adapter 2
    credentials:
        name: backend-qts-secret
    storage:
        - serviceLevel: pool1
          labels:
            performance: performance1
          features:
            tiering: Enable
sops:
    age:
        - recipient: age1sj99kupy552w8el4m2nydhpy89d5d7t968944dzac5xpu0k98duq8lqcf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZDdpS3Q0UFRZMGpqM21Z
            eGMwSEo1Z3k3TTRsOGZYQVVMRWpBc1J4b1FJCm5zSnJMRHhSckdvbFJYVXhSMGIz
            d0wzTmVibHdrRDZsZzZZMjB6dUhUcGMKLS0tIFpxcVVkN3ZQOGpqOHcrVjVzTGZI
            WmJXYkc2UXZadk9EZmR2YXF0TFJKY1UKamoFKhZZvBznbP85g8vgMGG1+9JZguuH
            KcmHGTzFdmkCHgO6qlBmqBMATMMp0AqSyQA5PJPgq/lDp6UcKOI2Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T23:04:34Z"
    mac: ENC[AES256_GCM,data:wUsMVv3uYIodNCZgFM7EFbnN9bROYwQMsNMqm4coRaVY5Oo7Z2MBGOCsW7dgsCXgL5g2Cf1CttUrxCqDSn+Ybn7cKda4aErwflDd2cryjT1f/Mts5m8OFlk9SgmPzac2LKglQnWH/uzWwxb0IfNl2lpPzGTxtHgg6xbD7tl6KtU=,iv:IM6TRPGq9ouXiz1cMgvKK7r/ubINzSFaX+7MJOiKeu4=,tag:idQWE7TVUseLR3jlxk1ADQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
