apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qnap-test
  namespace: default
  annotations:
    trident.qnap.io/Threshold: "90"
    trident.qnap.io/ThinAllocate: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: qnap-iscsi-perf1