apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-iscsi-perf1
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=performance1"
  fsType: "ext4"
  replacementTimeout: "120"
allowVolumeExpansion: true:wq!
