apiVersion: v1
kind: Service
metadata:
  name: traefik-ts
  namespace: kube-system
  annotations:
    tailscale.com/hostname: traefik
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: 8000
    - name: websecure
      port: 443
      targetPort: 8443
